//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golden_Ticket.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Golden_Ticket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coasterblurred {
            get {
                object obj = ResourceManager.GetObject("coasterblurred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate your Theme Park World/Sim Theme Park executable..
        /// </summary>
        internal static string FolderBrowser_Description {
            get {
                return ResourceManager.GetString("FolderBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim Theme Park.
        /// </summary>
        internal static string GameName_America {
            get {
                return ResourceManager.GetString("GameName_America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Park World.
        /// </summary>
        internal static string GameName_Europe {
            get {
                return ResourceManager.GetString("GameName_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a {0}/{1} folder to run this application..
        /// </summary>
        internal static string GetGame_Error_Message {
            get {
                return ResourceManager.GetString("GetGame_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Not Found.
        /// </summary>
        internal static string GetGame_Error_Title {
            get {
                return ResourceManager.GetString("GetGame_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Edition.
        /// </summary>
        internal static string GoldEdition {
            get {
                return ResourceManager.GetString("GoldEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/The-Buzzy-Project/Golden-Ticket/releases.
        /// </summary>
        internal static string GoldenTicket_ReleaseUrl {
            get {
                return ResourceManager.GetString("GoldenTicket_ReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.18.tar.xz.
        /// </summary>
        internal static string Patch_FakePatch_Url {
            get {
                return ResourceManager.GetString("Patch_FakePatch_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic patch.
        /// </summary>
        internal static string Patch_Generic_Name {
            get {
                return ResourceManager.GetString("Patch_Generic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/The-Buzzy-Project/Generic-Patch-Files/archive/master.zip.
        /// </summary>
        internal static string Patch_Generic_Url {
            get {
                return ResourceManager.GetString("Patch_Generic_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 8+ compatibility patch.
        /// </summary>
        internal static string Patch_Win8_Name {
            get {
                return ResourceManager.GetString("Patch_Win8_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/The-Buzzy-Project/8-10-Configs/archive/master.zip.
        /// </summary>
        internal static string Patch_Win8_Url {
            get {
                return ResourceManager.GetString("Patch_Win8_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Vista/7 compatibility patch.
        /// </summary>
        internal static string Patch_WinVista_Name {
            get {
                return ResourceManager.GetString("Patch_WinVista_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patched.
        /// </summary>
        internal static string Patched {
            get {
                return ResourceManager.GetString("Patched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Downloading ({1}%).
        /// </summary>
        internal static string Patcher_Downloading {
            get {
                return ResourceManager.GetString("Patcher_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Downloading.
        /// </summary>
        internal static string Patcher_DownloadingIndeterminate {
            get {
                return ResourceManager.GetString("Patcher_DownloadingIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Failed.
        /// </summary>
        internal static string Patcher_Failed {
            get {
                return ResourceManager.GetString("Patcher_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Installing ({1}%).
        /// </summary>
        internal static string Patcher_Installing {
            get {
                return ResourceManager.GetString("Patcher_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Installing.
        /// </summary>
        internal static string Patcher_InstallingIndeterminate {
            get {
                return ResourceManager.GetString("Patcher_InstallingIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Done.
        /// </summary>
        internal static string Patcher_Success {
            get {
                return ResourceManager.GetString("Patcher_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Export File.
        /// </summary>
        internal static string SpecsExport_Error_Title {
            get {
                return ResourceManager.GetString("SpecsExport_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Check for Updates.
        /// </summary>
        internal static string UpdateChecker_Error_Title {
            get {
                return ResourceManager.GetString("UpdateChecker_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for {0} is available. Would you like to download and install it now?.
        /// </summary>
        internal static string UpdateChecker_Message {
            get {
                return ResourceManager.GetString("UpdateChecker_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateChecker_Title {
            get {
                return ResourceManager.GetString("UpdateChecker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/The-Buzzy-Project/Golden-Ticket/master/version.json.
        /// </summary>
        internal static string UpdateChecker_Url {
            get {
                return ResourceManager.GetString("UpdateChecker_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
